Wanted/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Wanted import settings
from wantedapp.views import WantedListView

urlpatterns = [
    path('', WantedListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('wanted/', include('wantedapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wanted_list/urls.py
from django.urls import path

from wanted_list.views import WantedListView

app_name = 'wdlist'

urlpatterns = [
    path('list/', WantedListView.as_view(), name='list')
]

wantedapp/urls.py
from django.urls import path, reverse

from wantedapp.views import WantedListView, WantedCreateView, WantedDetailView, WantedUpdateView

app_name = "wantedapp"

urlpatterns = [
    # path('home/', reverse('wantedapp:home'), name='home'),
    path('create/', WantedCreateView.as_view(), name='create'),
    path('detail/<int:pk>', WantedDetailView.as_view(), name='detail'),
    path('update/<int:pk>', WantedUpdateView.as_view(), name='update'),
    path('list/', WantedListView.as_view(), name='list'),
]

wanted_list/models.py
from django.db import models

# Create your models here.

class test(models.Model):
    title = models.CharField(max_length=200, null=True)
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

wantedapp/models.py
from django.db import models

# Create your models here.

class Wanted(models.Model):
    image = models.ImageField(upload_to='wanted/', null=False)

    # Foregin Key
    job = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    work_place = models.CharField(max_length=200, null=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    end_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    address = models.CharField(max_length=200, null=True)

    like = models.IntegerField(null=True)
    compensation = models.IntegerField(null=True)
    content = models.TextField(null=True)

wantedapp/forms.py
from django.forms import ModelForm, forms, DateInput, DateField

from wantedapp.models import Wanted


class WantedCreationForm(ModelForm):
    end_date = DateField(widget=DateInput(format='%d/%m/%Y'), input_formats=('%d/%m/%Y',))

    class Meta:
        model = Wanted
        fields = ['image','job','company','country','work_place','address','end_date','compensation','content']

wanted_list/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView

from wanted_list.models import test


class WantedListView(ListView):
    model = test
    context_object_name = 'wantedapp'
    template_name = 'wantedapp/list.html'
    paginate_by = 5

wantedapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import path, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from wantedapp.forms import WantedCreationForm
from wantedapp.models import Wanted


class WantedCreateView(CreateView):
    model = Wanted
    form_class = WantedCreationForm
    template_name = 'wantedapp/create.html'

    def get_success_url(self):
        return reverse('wantedapp:list')

# class WantedUpdateView(UpdateView):
# class WantedDetailView(DetailView):

class WantedListView(ListView):
    model = Wanted
    context_object_name = 'wanted_list'
    template_name = 'wantedapp/list.html'

class WantedDetailView(DetailView):
    model = Wanted
    context_object_name = 'target_wanted'
    template_name = 'wantedapp/detail.html'

class WantedUpdateView(UpdateView):
    model = Wanted
    form_class = WantedCreationForm
    context_object_name = 'target_wanted'
    template_name = 'wantedapp/update.html'

    def get_success_url(self):
        return reverse('wantedapp:detail', kwargs={'pk': self.object.pk})

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<!--<body>-->
<body style="font-family: 'NanumSquareOTFRegular', Arial;">
    {% include 'header.html' %}

    {% block content %}

    {% endblock %}

    {% include 'footer.html' %}
</body>

</html>

templates/footer.html
<div class="wanted_footer text-center" style="margin:3rem auto;">
    <a href="" alt="" style="text-align:left">
        <!-- Need Image -->
        wanted
    </a>

    <a href="">
        이용약관
    </a>

    <a href="">
        개인정보 처리방침
    </a>

    <a href="">
        고객센터
    </a>

    <a href="">
        투자정보
    </a>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
    <title>Wanted</title>

    <!-- Bootstrap Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- Base CSS Link -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">


    <style>
        @font-face {
            font-family: 'NanumSquareOTFBold';
            src: local('NanumSquareOTFBold'),
            url("{% static 'fonts/NanumSquareOTFBold.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareOTFExtraBold';
            src: local('NanumSquareOTFExtraBold'),
            url("{% static 'fonts/NanumSquareOTFExtraBold.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareOTFLight';
            src: local('NanumSquareOTFLight'),
            url("{% static 'fonts/NanumSquareOTFLight.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareOTFRegular';
            src: local('NanumSquareOTFRegular'),
            url("{% static 'fonts/NanumSquareOTFRegular.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="wanted_header">

    <div class="wanted_header_logo">
        <a href="" alt="">
            <!-- Need Image -->
            wanted
        </a>
    </div>

    <div class="wanted_header_nav_list">
        <a href="{% url 'wantedapp:list' %}" class="wanted_header_nav">
            탐색
        </a>

        <a href="" class="wanted_header_nav">
            커리어 성장
        </a>

        <a href="" class="wanted_header_nav">
            직군별 연봉
        </a>

        <a href="" class="wanted_header_nav">
            이력서
        </a>

        <a href="" class="wanted_header_nav">
            매치업
        </a>

        <a href="" class="wanted_header_nav">
            프리랜서
        </a>
    </div>

    <div class="wanted_header_profile">
        <a href="">
            My Page
        </a>
    </div>

</div>

wanted_list/templates/wanted_list/list.html
{% extends 'base.html' %}

{% block content %}

<p>
    WD_LIST
</p>


{% endblock %}

wantedapp/templates/wantedapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="text-center">
        <h4>
            Create Wanted
        </h4>
    </div>

    <div class="text-center">
        <form action="{% url 'wantedapp:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary">
        </form>
    </div>
</div>


{% endblock %}

wantedapp/templates/wantedapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="job_detail" style="width:50%; margin: auto auto;">

        <img src="{{ target_wanted.image.url }}" alt="" style="height: 30rem; width: 100%; object-fit: cover;">

        <div class="wanted_main_context">
            <h4> {{ target_wanted.job }} </h4>
            <h6> {{ target_wanted.company }} <span> | {{ target_wanted.work_place }} · {{ target_wanted.country }}</span></h6>
        </div>

        <hr>

        <div class="wanted_detail_context">
            {{ target_wanted.content }}
        </div>

        <hr>

        <div class="wanted_sub_context">
            <h6><span class="header">마감일</span><span class="body">{{ target_wanted.end_date | date:"Y.m.d"}}</span></h6>
            <h6><span class="header">근무장소</span><span class="body">{{ target_wanted.address }}</span></h6>

            <div class="company_box">
                <button type="button">
                    <div class="box_logo" style="background-image: url('{{ target_wanted.image.url }}');"></div>

                    <div class="box_context">
                        <h5> {{ target_wanted.company}} </h5>
                        <h6> IT, 컨텐츠</h6>
                    </div>
                </button>

                <button type="button">
                    <a href="#" class="btn btn-primary">
                        팔로우
                    </a>
                </button>
            </div>
        </div>

        <hr>

        <div style="text-align: center;">
            <a href="{% url 'wantedapp:update' pk=target_wanted.pk %}"
               class="btn btn-primary rounded-pill col-3">
                Update Wanted
            </a>
        </div>

    </div>
</div>


{% endblock %}

wantedapp/templates/wantedapp/home.html
{% extends 'base.html' %}

{% block content %}

<h2 style="text-align: center">
    HOME
</h2>

{% endblock %}

wantedapp/templates/wantedapp/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

<style xmlns="http://www.w3.org/1999/html">

</style>

{% if wanted_list %}
    <div class="job_container" style="width:80%">
        <ul class="job_list">
        {% for wanted in wanted_list %}
            <li style="width:180px; height:330px;">
<!--                <div style="display:inline-block; width:200px; height:270px;">-->
                <div>
                    <a href="{% url 'wantedapp:detail' pk=wanted.pk %}">
                        <header style="display:inline-block; width:180px; height:150px;
                                        background-image: url({{ wanted.image.url }}); background-size:100% 100%;">
                        </header>
                        <div class="job-card-content" style="height: 150px;">
                            <div class="job-card-position">{{ wanted.job }}</div>
                            <div class="job-card-company">{{ wanted.company }}</div>
                            <div class="job-card-location">
                                <span>{{ wanted.country }}</span>
                                <span> - </span>
                                <span>{{ wanted.work_place }}</span>
                            </div>
                            <div class="job-card-reward">채용보상금 : {{ wanted.compensation }}원</div>
                        </div>
                    </a>
                </div>
            </li>
        {% endfor %}
        </ul>
    </div>
{% else %}
    <div class="text-center">
        <h1>No Wanted YET!!!</h1>
    </div>
{% endif %}

    <div class="text-center">
        <a href="{% url 'wantedapp:create' %}" class="btn btn-dark">
            Create Wanted
        </a>
    </div>



{% endblock %}

wantedapp/templates/wantedapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div>
    <div class="text-center">
        <h4>
            Update Wanted
        </h4>
    </div>

    <div class="text-center">
        <form action="{% url 'wantedapp:update' pk=target_wanted.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary">
        </form>
    </div>
</div>


{% endblock %}